# Generated by Django 5.0.4 on 2024-05-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='added',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='published',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
